M = [
"Upper Chest",
"Middle Chest",
"Lower Chest",
"Front Delt",
"Mid Delt",
"Rear Delt",
"Tricep Long Head",
"Tricep Medial Head",
"Tricep Lateral Head",
"Bicep Long Head",
"Bicep Short Head",
"Bicep Brachialis ",
"Forearm",
"Upper Abs",
"Lower Abs",
"Obliques",
"Serratus",
"Lats",
"Rhomboid",
"Teres",
"Upper Trap",
"Lower Traps",
"Spinae Erector",
"Lower Back",
"Quads",
"Glutes",
"Hamstrings",
"Calves",
"Adductor",
"Abductor"]

for i in M:
    print(f"INSERT INTO MUSCLE(id, muscle) VALUES(NULL,'{i}');")